
# Site settings
title: "Andika Perbawa"
email: andika.perbawa@gmail.com

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
    
plugins:
  - jekyll-sitemap
